# Generated by Django 3.0.3 on 2020-06-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_area', models.CharField(blank=True, max_length=255, null=True)),
                ('second_area', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('area1', models.CharField(blank=True, max_length=255, null=True)),
                ('area2', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('fee', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('is_class', models.IntegerField()),
                ('is_period', models.IntegerField()),
                ('like_cnt', models.IntegerField()),
                ('max_person', models.IntegerField()),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('now_person', models.IntegerField()),
                ('period_date', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_url', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField()),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('view_cnt', models.IntegerField()),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingImages',
            fields=[
                ('meeting_images_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreeableness', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('extraversion', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('openness', models.IntegerField()),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ages', models.IntegerField()),
                ('area1', models.CharField(blank=True, max_length=255, null=True)),
                ('area2', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField()),
                ('is_inst', models.IntegerField()),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Category')),
            ],
            options={
                'db_table': 'interest_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeMeeting',
            fields=[
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Meeting')),
            ],
            options={
                'db_table': 'like_meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Meeting')),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'user_meeting',
                'managed': False,
            },
        ),
    ]
